version: '3'
services:
  driven-eats:
    build:
      context: ../java-driven-eats
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
   

